package com.InfraDesk.enums;

public enum PermissionCode {
    EMPLOYEE_VIEW,
    EMPLOYEE_MANAGE,
    EMPLOYEE_ADMIN,

    TICKET_VIEW,
    TICKET_MANAGE,
    TICKET_ADMIN,

    ASSET_VIEW,
    ASSET_MANAGE,
    ASSET_ADMIN,

    DEPARTMENT_VIEW,
    DEPARTMENT_MANAGE,
    DEPARTMENT_ADMIN,

    SITE_VIEW,
    SITE_MANAGE,
    SITE_ADMIN,

    LOCATION_VIEW,
    LOCATION_MANAGE,
    LOCATION_ADMIN,

    REQUEST_VIEW,
    REQUEST_MANAGE,
    REQUEST_ADMIN,

    COMPANY_VIEW,
    COMPANY_MANAGE,
    COMPANY_CONFIGURE
}
